services:
  jupyter:
    image: jupyter_env_image
    build: .
    

    ports:
      - "8888:8888"
    
    volumes:
      - ./workspaces:/workspaces

    command : ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]


