version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  jupyter:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    
    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # 로컬 변수를 사용하여 경로 지정
      - ..:/workspaces/${LOCAL_WORKSPACE_NAME}:cached
    working_dir: /workspaces/${LOCAL_WORKSPACE_NAME}
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
 
